export async function seed(knex) {
  const now = new Date().toISOString();

  await knex('applications').del();
  await knex('opportunities').del();
  await knex('users').del();

  const hashedPassword = '$2a$12$ILiNrGYbDMWuxq8TVddp0OTL4bVKVJXbQqySjAmEbNLot8rPsGWr6';

  const users = [
    {
      id: 1,
      email: 'admin@admin.com',
      verified_email: 1,
      password: hashedPassword,
      user_type: 'ADMIN',
      status: 'ATIVO',
      full_name: 'Administrador do Sistema',
      bio: 'Administrador do sistema Zircon.',
      phone_number: '(11)99999-9999',
      document_type: 'CPF',
      document_number: '12345678900',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    {
      id: 2,
      email: 'contato@claritylabs.com',
      verified_email: 1,
      password: hashedPassword,
      user_type: 'EMPRESA',
      status: 'ATIVO',
      full_name: 'Clarity Labs',
      bio: 'Empresa de produtos digitais e inovação.',
      phone_number: '(11)98888-1111',
      document_type: 'CNPJ',
      document_number: '11111111111111',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    {
      id: 3,
      email: 'rh@nortedigital.com',
      verified_email: 1,
      password: hashedPassword,
      user_type: 'EMPRESA',
      status: 'ATIVO',
      full_name: 'Norte Digital',
      bio: 'Agência digital com foco em produto e experiência.',
      phone_number: '(21)97777-2222',
      document_type: 'CNPJ',
      document_number: '22222222222222',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    {
      id: 4,
      email: 'caio@zircon.com',
      verified_email: 1,
      password: hashedPassword,
      user_type: 'PROFISSIONAL',
      status: 'ATIVO',
      full_name: 'Caio Silva',
      bio: 'Designer e especialista em experiência digital.',
      phone_number: '(11)96666-3333',
      document_type: 'CPF',
      document_number: '52998224725',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    {
      id: 5,
      email: 'jobs@orbetecnologia.com',
      verified_email: 1,
      password: hashedPassword,
      user_type: 'EMPRESA',
      status: 'ATIVO',
      full_name: 'Orbe Tecnologia',
      bio: 'Consultoria tecnológica focada em transformação digital.',
      phone_number: '(31)95555-4444',
      document_type: 'CNPJ',
      document_number: '33333333333333',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
  ];

  await knex('users').insert(users);

  await knex('opportunities').insert([
    {
      user_id: 2,
      company_sector: 'Clarity Labs',
      job_title: 'Product Designer Pleno',
      job_description: 'Buscamos uma pessoa designer para transformar problemas complexos em experiências digitais simples e acessíveis. Você trabalhará perto de times de produto, UX e engenharia.',
      payment_value: 8500,
      benefits_text: 'Home office · Vale alimentação · Plano de saúde · Horários flexíveis',
      work_modality: 'HOME_OFFICE',
      status: 'ATIVA',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    {
      user_id: 3,
      company_sector: 'Norte Digital',
      job_title: 'UX Researcher',
      job_description: 'Ajudaremos a mapear necessidades reais dos usuários e transformar insights em decisões estratégicas. O papel envolve entrevistas, estudo de comportamento e prototipação.',
      payment_value: 7200,
      benefits_text: 'Híbrido · Reembolso de transporte · Mentoria · Bônus anual',
      work_modality: 'HIBRIDO',
      status: 'ATIVA',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    {
      user_id: 5,
      company_sector: 'Orbe Tecnologia',
      job_title: 'Service Designer',
      job_description: 'Vamos criar jornadas mais humanas e intuitivas em projetos de transformação digital. O time trabalha com pesquisa, mapeamento de serviço e prototipação.',
      payment_value: 9100,
      benefits_text: 'Remote-first · Aulas e workshops · Descanso semanal · PLR',
      work_modality: 'HOME_OFFICE',
      status: 'ATIVA',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    {
      user_id: 2,
      company_sector: 'Clarity Labs',
      job_title: 'Desenvolvedor(a) Front-end',
      job_description: 'Produzir interfaces modernas, acessíveis e bem estruturadas para os produtos do cliente. Trabalhamos com React, TypeScript e colaboração entre design e código.',
      payment_value: 9600,
      benefits_text: 'Home office · Vale refeição · Ambiente colaborativo · Bônus trimestral',
      work_modality: 'HIBRIDO',
      status: 'ATIVA',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
    {
      user_id: 3,
      company_sector: 'Norte Digital',
      job_title: 'Analista de Dados Júnior',
      job_description: 'Transformar dados em histórias e métricas que auxiliem decisões de produto. Traga curiosidade, organização e vontade de aprender SQL e visualização.',
      payment_value: 5800,
      benefits_text: 'Home office · Auxílio home office · Mentoria · Plano de saúde',
      work_modality: 'HOME_OFFICE',
      status: 'ATIVA',
      created_at: now,
      updated_at: now,
      deleted_at: null,
    },
  ]);
}